### ISSUE TITLE
Can't run the example `moon run '(add 1 2)'`.

### ISSUE THREAD

**Issue by AnthonyJacob** [MaiaVictor/moon-tool#1]
Running the example on windows 10 and powershell result in:

```shell
PS D:\Moon-Elm\tests\moon-elm> moon run '(add 1 2)'
C:\Users\Anthony\AppData\Roaming\npm\node_modules\moon-tool\moon-tool.js:22
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by VictorTaelin** [comment]
Oh, I think I forgot to babelify this project. Any chance you could do it? Same thing as `moon-lang`, just add .babelrc, add the dev dependencies, add `build` to `package.json` and build it...
